# Generated by Django 2.2.1 on 2019-06-04 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190604_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default=datetime.datetime(2019, 6, 4, 13, 29, 44, 765581)),
        ),
    ]
