# Generated by Django 2.2.1 on 2019-06-04 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190604_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default=datetime.datetime(2019, 6, 4, 13, 30, 33, 359237)),
        ),
    ]
