# Generated by Django 2.2.1 on 2019-06-04 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190604_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default=datetime.datetime(2019, 6, 4, 17, 19, 1, 646255)),
        ),
    ]
